// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qAHxie4pG5fD4zBBMRe14U
// Component: gQsQhUP-0Mr9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CartComponent } from "@plasmicpkgs/commerce";
import { ProductBox } from "@plasmicpkgs/commerce";
import { ProductMedia } from "@plasmicpkgs/commerce";
import { ProductTextField } from "@plasmicpkgs/commerce";
import { ProductPriceComponent } from "@plasmicpkgs/commerce";
import { ProductVariantPicker } from "@plasmicpkgs/commerce";
import { ProductQuantity } from "@plasmicpkgs/commerce";
import Select from "../../Select"; // plasmic-import: XdSsvWChsiRe/component
import Select__Option from "../../Select__Option"; // plasmic-import: bWwYmGoxXW2h/component
import { AddToCartButton } from "@plasmicpkgs/commerce";
import Button from "../../Button"; // plasmic-import: A1kRSkjb2t4z/component

import { useScreenVariants as useScreenVariantszwVhShyf8Nk } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -zwVhSHYF8nk/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: qAHxie4pG5fD4zBBMRe14U/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: gQsQhUP-0Mr9/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: j06qeqk6oWDn/icon
import PlayingCardHeartShapesvgIcon from "./icons/PlasmicIcon__PlayingCardHeartShapesvg"; // plasmic-import: r4meCPR77qct/icon
import BlackCommentsBubbleSvgrepoComsvgIcon from "./icons/PlasmicIcon__BlackCommentsBubbleSvgrepoComsvg"; // plasmic-import: ZvPDMgcKYxuI/icon
import CartOSvgrepoComsvgIcon from "./icons/PlasmicIcon__CartOSvgrepoComsvg"; // plasmic-import: 8JXMTNyOhaGF/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 8dz3Z8q7DeJr/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  cart?: Flex__<typeof CartComponent>;
  foreground2?: Flex__<"div">;
  select?: Flex__<typeof Select>;
  select2?: Flex__<typeof Select>;
  select3?: Flex__<typeof Select>;
  select4?: Flex__<typeof Select>;
  select5?: Flex__<typeof Select>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select4.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select5.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszwVhShyf8Nk()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__ge0Bl)}>
            <div className={classNames(projectcss.all, sty.freeBox__ijcEl)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__j58Zb)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qHga)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__s8KJf)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__gVc2C
                      )}
                    >
                      {"Logo"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__maSgg)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__swFqK)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__cBn2I
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rjh8K
                            )}
                            role={"img"}
                          />
                        ) : null}
                        {false ? (
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ktnHn
                            )}
                            role={"img"}
                          />
                        ) : null}
                        <PlayingCardHeartShapesvgIcon
                          className={classNames(projectcss.all, sty.svg__fqzO)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__re81U
                        )}
                      >
                        {false ? (
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qdLvt
                            )}
                            role={"img"}
                          />
                        ) : null}
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vUfk2
                          )}
                        >
                          {"Liked by 32k"}
                        </div>
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__ugv2
                          )}
                          component={Link}
                          platform={"nextjs"}
                        >
                          <BlackCommentsBubbleSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mRvmN
                            )}
                            role={"img"}
                          />

                          {false ? (
                            <IconIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vu2R
                              )}
                              role={"img"}
                            />
                          ) : null}
                          {false ? (
                            <IconIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__kOdb
                              )}
                              role={"img"}
                            />
                          ) : null}
                        </PlasmicLink__>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cbHi
                          )}
                        >
                          {"312 Comments"}
                        </div>
                        {false ? (
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wpdbY
                            )}
                            role={"img"}
                          />
                        ) : null}
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9Lub6
                          )}
                        >
                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link___8S2CK
                            )}
                            component={Link}
                            platform={"nextjs"}
                          >
                            {false ? (
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__fiBtv
                                )}
                                role={"img"}
                              />
                            ) : null}
                            {false ? (
                              <IconIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__xF3JH
                                )}
                                role={"img"}
                              />
                            ) : null}
                            <CartOSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__cfsKt
                              )}
                              role={"img"}
                            />
                          </PlasmicLink__>
                          <CartComponent
                            data-plasmic-name={"cart"}
                            data-plasmic-override={overrides.cart}
                            className={classNames("__wab_instance", sty.cart)}
                            field={"Size"}
                            hideIfIsEmpty={true}
                          />
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hdCuJ)}>
                <div className={classNames(projectcss.all, sty.freeBox__xhf9)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rnkaU)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__kxbRa
                      )}
                    >
                      {"Lorem ipsum dolor\nsit amet."}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yTeQx
                      )}
                    >
                      {
                        "Nosi accusamus rem assumenda incidut enim ea.\nSoluta explicabo desertunt."
                      }
                    </div>
                  </Stack__>
                </div>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__c68Ph)}
              >
                <Stack__
                  as={PlasmicLink__}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__wgpx6
                  )}
                  component={Link}
                  href={"#shop-look"}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__pAz)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___01Td9
                    )}
                  >
                    {"Shop Look"}
                  </div>
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___6NTxn)}
                      role={"img"}
                    />
                  ) : null}
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___8TVwu)}>
            <div className={classNames(projectcss.all, sty.freeBox__yktA)} />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__gMmYg)}>
            <div className={classNames(projectcss.all, sty.freeBox__ct3S)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zyHyf)}
                id={"shop-look"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ebiPf)}>
                  <ProductBox
                    className={classNames(
                      "__wab_instance",
                      sty.productBox__ugazl
                    )}
                    id={"oxford-loafers"}
                  >
                    <DataCtxReader__>
                      {$ctx => (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__tsHVk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__s0Qw
                            )}
                          >
                            <ProductMedia
                              className={classNames(
                                "__wab_instance",
                                sty.productMedia__iw7Lh
                              )}
                            />
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.column__p3EOu
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__l1XPo)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? "150px"
                                  : "200px"
                              }
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/copy_of_t_7/images/sprinkles1Cd2Da2A2Svg.svg",
                                fullWidth: 180,
                                fullHeight: 150,
                                aspectRatio: 1.198795
                              }}
                            />

                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                sty.h2___5Prrj
                              )}
                            >
                              <ProductTextField
                                className={classNames(
                                  "__wab_instance",
                                  sty.productTextField__zUv9P
                                )}
                                field={"name"}
                              />
                            </h2>
                            <ProductTextField
                              className={classNames(
                                "__wab_instance",
                                sty.productTextField__jpWo
                              )}
                              field={"description"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.columns__bPrtL
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__zdeXq
                                )}
                              >
                                <h6
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h6,
                                    sty.h6__aeSgi
                                  )}
                                >
                                  <ProductPriceComponent
                                    className={classNames(
                                      "__wab_instance",
                                      sty.productPrice__zVlt8
                                    )}
                                  />
                                </h6>
                                <ProductVariantPicker
                                  className={classNames(
                                    "__wab_instance",
                                    sty.productVariantPicker__i6WSd
                                  )}
                                />
                              </div>
                            </div>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns__qdxOs
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__yA57H
                                )}
                              >
                                <ProductQuantity
                                  className={classNames(
                                    "__wab_instance",
                                    sty.productQuantity__oD87
                                  )}
                                >
                                  <Select
                                    data-plasmic-name={"select"}
                                    data-plasmic-override={overrides.select}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.select
                                    )}
                                    onChange={(...eventArgs) => {
                                      generateStateOnChangeProp($state, [
                                        "select",
                                        "value"
                                      ])(eventArgs[0]);
                                    }}
                                    placeholder={"1"}
                                    value={generateStateValueProp($state, [
                                      "select",
                                      "value"
                                    ])}
                                  />
                                </ProductQuantity>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__kdlz7
                                )}
                              >
                                <AddToCartButton
                                  className={classNames(
                                    "__wab_instance",
                                    sty.addToCartButton__z2Lww
                                  )}
                                >
                                  <Button
                                    className={classNames(
                                      "__wab_instance",
                                      sty.button__dpHx3
                                    )}
                                    color={"pink"}
                                    submitsForm={true}
                                  >
                                    {"ADD TO CART"}
                                  </Button>
                                </AddToCartButton>
                              </div>
                            </Stack__>
                          </Stack__>
                        </div>
                      )}
                    </DataCtxReader__>
                  </ProductBox>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jmE1R)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "90px"
                      : "106px"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/copy_of_t_7/images/sprinkles2D589E9E91Svg.svg",
                    fullWidth: 138,
                    fullHeight: 150,
                    aspectRatio: 0.921739
                  }}
                />
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ywJv0)} />

          <div className={classNames(projectcss.all, sty.freeBox___7As7M)}>
            <div className={classNames(projectcss.all, sty.freeBox__xkzh0)}>
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__mCmc1)}
                id={"lorem-ankle-length"}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__jgrqe)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.column__yvQe)}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.h2__xdaIk
                          )}
                        >
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField__eEyNb
                            )}
                            field={"name"}
                          />
                        </h2>
                        <ProductTextField
                          className={classNames(
                            "__wab_instance",
                            sty.productTextField__dnskO
                          )}
                          field={"description"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns___5J3Re
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column___3NmRz
                            )}
                          >
                            <h6
                              className={classNames(
                                projectcss.all,
                                projectcss.h6,
                                sty.h6__qen6B
                              )}
                            >
                              <ProductPriceComponent
                                className={classNames(
                                  "__wab_instance",
                                  sty.productPrice__vZci
                                )}
                              />
                            </h6>
                            <ProductVariantPicker
                              className={classNames(
                                "__wab_instance",
                                sty.productVariantPicker__grNy
                              )}
                            />
                          </div>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.columns___7F2Pe
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__jyy3F
                            )}
                          >
                            <ProductQuantity
                              className={classNames(
                                "__wab_instance",
                                sty.productQuantity__uK1Rs
                              )}
                            >
                              <Select
                                data-plasmic-name={"select2"}
                                data-plasmic-override={overrides.select2}
                                className={classNames(
                                  "__wab_instance",
                                  sty.select2
                                )}
                                onChange={(...eventArgs) => {
                                  generateStateOnChangeProp($state, [
                                    "select2",
                                    "value"
                                  ])(eventArgs[0]);
                                }}
                                placeholder={"1"}
                                value={generateStateValueProp($state, [
                                  "select2",
                                  "value"
                                ])}
                              />
                            </ProductQuantity>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__t8Mqi
                            )}
                          >
                            <AddToCartButton
                              className={classNames(
                                "__wab_instance",
                                sty.addToCartButton___0B9Wp
                              )}
                            >
                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__tTxNd
                                )}
                                color={"yellow"}
                                submitsForm={true}
                              >
                                {"ADD TO CART"}
                              </Button>
                            </AddToCartButton>
                          </div>
                        </Stack__>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__q1X8W
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__akd6D)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/copy_of_t_7/images/anklepng.png",
                            fullWidth: 740,
                            fullHeight: 1000,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </Stack__>
                  )}
                </DataCtxReader__>
              </ProductBox>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ilTmd)} />

          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__muXrJ)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__wov2O)}>
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__pc0Ze)}
                id={"baseball-cap"}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(projectcss.all, sty.columns__y4VOy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mavXj
                        )}
                      >
                        <ProductMedia
                          className={classNames(
                            "__wab_instance",
                            sty.productMedia__e2Cq6
                          )}
                        />
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.column__oprcf
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__m562)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "150px"
                              : "200px"
                          }
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/copy_of_t_7/images/sprinkles1Cd2Da2A2Svg.svg",
                            fullWidth: 180,
                            fullHeight: 150,
                            aspectRatio: 1.198795
                          }}
                        />

                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.h2__jWJwH
                          )}
                        >
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField___2MjH
                            )}
                            field={"name"}
                          />
                        </h2>
                        <ProductTextField
                          className={classNames(
                            "__wab_instance",
                            sty.productTextField__waiBy
                          )}
                          field={"description"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__kt2Fh
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__zSVfk
                            )}
                          >
                            <h6
                              className={classNames(
                                projectcss.all,
                                projectcss.h6,
                                sty.h6__bzBo2
                              )}
                            >
                              <ProductPriceComponent
                                className={classNames(
                                  "__wab_instance",
                                  sty.productPrice__gdObx
                                )}
                              />
                            </h6>
                            <ProductVariantPicker
                              className={classNames(
                                "__wab_instance",
                                sty.productVariantPicker__cmXxw
                              )}
                            />
                          </div>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.columns___6O5Pb
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__pEmPu
                            )}
                          >
                            <ProductQuantity
                              className={classNames(
                                "__wab_instance",
                                sty.productQuantity__iAjJw
                              )}
                            >
                              <Select
                                data-plasmic-name={"select3"}
                                data-plasmic-override={overrides.select3}
                                className={classNames(
                                  "__wab_instance",
                                  sty.select3
                                )}
                                onChange={(...eventArgs) => {
                                  generateStateOnChangeProp($state, [
                                    "select3",
                                    "value"
                                  ])(eventArgs[0]);
                                }}
                                placeholder={"1"}
                                value={generateStateValueProp($state, [
                                  "select3",
                                  "value"
                                ])}
                              />
                            </ProductQuantity>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__jBtZo
                            )}
                          >
                            <AddToCartButton
                              className={classNames(
                                "__wab_instance",
                                sty.addToCartButton__bBftN
                              )}
                            >
                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__cLjg
                                )}
                                color={"pink"}
                                submitsForm={true}
                              >
                                {"ADD TO CART"}
                              </Button>
                            </AddToCartButton>
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                  )}
                </DataCtxReader__>
              </ProductBox>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__sq0IO)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "90px"
                  : "106px"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/copy_of_t_7/images/sprinkles2D589E9E91Svg.svg",
                fullWidth: 138,
                fullHeight: 150,
                aspectRatio: 0.921739
              }}
            />
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox__bku3I)} />

          <div className={classNames(projectcss.all, sty.freeBox__n3D4Q)}>
            <div className={classNames(projectcss.all, sty.freeBox__hdulq)}>
              <div className={classNames(projectcss.all, sty.freeBox__uZpBx)}>
                <ProductBox
                  className={classNames(
                    "__wab_instance",
                    sty.productBox__c8SsU
                  )}
                  id={"triangle-bikini-top"}
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__h9Jz5
                        )}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.column__fYqyP
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              sty.h2__mxcGj
                            )}
                          >
                            <ProductTextField
                              className={classNames(
                                "__wab_instance",
                                sty.productTextField___3I2YG
                              )}
                              field={"name"}
                            />
                          </h2>
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField__pje
                            )}
                            field={"description"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.columns__upNxk
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__fofUu
                              )}
                            >
                              <h6
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h6,
                                  sty.h6__m67CX
                                )}
                              >
                                <ProductPriceComponent
                                  className={classNames(
                                    "__wab_instance",
                                    sty.productPrice__gDl5S
                                  )}
                                />
                              </h6>
                              <ProductVariantPicker
                                className={classNames(
                                  "__wab_instance",
                                  sty.productVariantPicker__hj3Kb
                                )}
                              />
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.columns___4BsO
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__zB9Qo
                              )}
                            >
                              <ProductQuantity
                                className={classNames(
                                  "__wab_instance",
                                  sty.productQuantity__g9ZJ
                                )}
                              >
                                <Select
                                  data-plasmic-name={"select4"}
                                  data-plasmic-override={overrides.select4}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.select4
                                  )}
                                  onChange={(...eventArgs) => {
                                    generateStateOnChangeProp($state, [
                                      "select4",
                                      "value"
                                    ])(eventArgs[0]);
                                  }}
                                  placeholder={"1"}
                                  value={generateStateValueProp($state, [
                                    "select4",
                                    "value"
                                  ])}
                                />
                              </ProductQuantity>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__pl5A8
                              )}
                            >
                              <AddToCartButton
                                className={classNames(
                                  "__wab_instance",
                                  sty.addToCartButton__ygs7N
                                )}
                              >
                                <Button
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button__nwBiz
                                  )}
                                  color={"yellow"}
                                  submitsForm={true}
                                >
                                  {"ADD TO CART"}
                                </Button>
                              </AddToCartButton>
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__iurfF
                          )}
                        >
                          <ProductMedia
                            className={classNames(
                              "__wab_instance",
                              sty.productMedia__w0PUr
                            )}
                          />
                        </div>
                      </div>
                    )}
                  </DataCtxReader__>
                </ProductBox>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__fij5R)} />

          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__aveWu)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__wqMej)}>
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__cpEsS)}
                id={"short-blazer"}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(projectcss.all, sty.columns__tsUoE)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__hgI3)}
                      >
                        <ProductMedia
                          className={classNames(
                            "__wab_instance",
                            sty.productMedia__i7HaZ
                          )}
                        />
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.column___30Gd5
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__khsT2)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "150px"
                              : "200px"
                          }
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/copy_of_t_7/images/sprinkles1Cd2Da2A2Svg.svg",
                            fullWidth: 180,
                            fullHeight: 150,
                            aspectRatio: 1.198795
                          }}
                        />

                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.h2__buhEo
                          )}
                        >
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField__tKVhg
                            )}
                            field={"name"}
                          />
                        </h2>
                        <ProductTextField
                          className={classNames(
                            "__wab_instance",
                            sty.productTextField__ccXiN
                          )}
                          field={"description"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__kdKd2
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__dj7By
                            )}
                          >
                            <h6
                              className={classNames(
                                projectcss.all,
                                projectcss.h6,
                                sty.h6__lxNC
                              )}
                            >
                              <ProductPriceComponent
                                className={classNames(
                                  "__wab_instance",
                                  sty.productPrice__jPj8
                                )}
                              />
                            </h6>
                            <ProductVariantPicker
                              className={classNames(
                                "__wab_instance",
                                sty.productVariantPicker__oQBt2
                              )}
                            />
                          </div>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.columns__vmqsh
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__pDrlI
                            )}
                          >
                            <ProductQuantity
                              className={classNames(
                                "__wab_instance",
                                sty.productQuantity__ehO7S
                              )}
                            >
                              <Select
                                data-plasmic-name={"select5"}
                                data-plasmic-override={overrides.select5}
                                className={classNames(
                                  "__wab_instance",
                                  sty.select5
                                )}
                                onChange={(...eventArgs) => {
                                  generateStateOnChangeProp($state, [
                                    "select5",
                                    "value"
                                  ])(eventArgs[0]);
                                }}
                                placeholder={"1"}
                                value={generateStateValueProp($state, [
                                  "select5",
                                  "value"
                                ])}
                              />
                            </ProductQuantity>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__xFhOt
                            )}
                          >
                            <AddToCartButton
                              className={classNames(
                                "__wab_instance",
                                sty.addToCartButton___7JMGt
                              )}
                            >
                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button___4LmVy
                                )}
                                color={"pink"}
                                submitsForm={true}
                              >
                                {"ADD TO CART"}
                              </Button>
                            </AddToCartButton>
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                  )}
                </DataCtxReader__>
              </ProductBox>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__fvvwi)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "90px"
                  : "166px"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/copy_of_t_7/images/sprinkles35Ed71774Svg.svg",
                fullWidth: 130,
                fullHeight: 150,
                aspectRatio: 0.865591
              }}
            />
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__cqdD2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__hOfAk)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jVnC)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bdvoA
                  )}
                >
                  {"\u00c2\u00a9 Company. All rights reserved. "}
                </div>
              </Stack__>
            </div>
          </Stack__>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "cart",
    "foreground2",
    "select",
    "select2",
    "select3",
    "select4",
    "select5"
  ],
  cart: ["cart"],
  foreground2: ["foreground2"],
  select: ["select"],
  select2: ["select2"],
  select3: ["select3"],
  select4: ["select4"],
  select5: ["select5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cart: typeof CartComponent;
  foreground2: "div";
  select: typeof Select;
  select2: typeof Select;
  select3: typeof Select;
  select4: typeof Select;
  select5: typeof Select;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cart: makeNodeComponent("cart"),
    foreground2: makeNodeComponent("foreground2"),
    select: makeNodeComponent("select"),
    select2: makeNodeComponent("select2"),
    select3: makeNodeComponent("select3"),
    select4: makeNodeComponent("select4"),
    select5: makeNodeComponent("select5"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
